Support Ruby 4.0
cgi is no longer a default gem in 4.0 (except for cgi/escape) so we need
to include it in the gemspec

Without this, we get the following error when running the test suite
against Ruby 4.0

```
NoMethodError:
  undefined method 'parse' for class CGI
```